name: My First GitHub Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    stratergy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run Tests
        run: |
          python -m pytest addition_python.py
