name: BuildImageandPush

on:
  push:
    paths:
      - Dockerfile
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build and Push
        run: |
          echo "Building Image"
          echo "${{ secrets.DOCKERPW}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
          docker push nisanthkp90/githubactionimage:v.1
