name: BuildImageandPush

on:
  push:
    paths:
      - Dockerfile
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: repo checkout

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERPW }}

      - name: Build and Tag Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mygithubaction:latest .

      - name: Push Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/mygithubaction:latest
